### PR TITLE
setNamespace() is not mandatory in the Cache interface

### PR DESCRIPTION
**Pull request by quazardous**
Provider should allow cache without namespace

### CODE REVIEW

**Comment by sergiors** [comment]
😍

**Comment by sergiors** [comment]
I will release the 2.0.2 version soon

**Comment by quazardous** [comment]
thx !

**Comment by sergiors** [comment]
hey dude! https://github.com/sergiors/doctrine-cache-service-provider/releases/tag/2.0.2
💛
let's go do that issue https://github.com/sergiors/doctrine-orm-service-provider/issues/1

**Pull request merged**
